#!/usr/bin/with-contenv bash
# shellcheck shell=bash

JAVAMEM=${MAXMEM:-512}
PORT=$(jq -r '.adminPortNumber' < /config/preferences.json)

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT:-2203}" \
        cd /app/ubooquity s6-setuidgid abc java -Xmx"$JAVAMEM"m \
        -jar /app/ubooquity/Ubooquity.jar \
        --headless --host 0.0.0.0 --remoteadmin \
        --workdir /config
