#!/usr/bin/with-contenv bash

JAVAMEM=${MAXMEM:-512}

cd /app/ubooquity || exit

exec \
	s6-setuidgid abc java -Xmx"$JAVAMEM"m \
	-jar /app/ubooquity/Ubooquity.jar \
	--headless --host 0.0.0.0 --remoteadmin \
	--workdir /config
