#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	config/fonts

# copy config
[[ ! -e /config/preferences.xml ]] && \
	cp /defaults/preferences.xml /config/preferences.xml

# permissions
chown -R abc:abc \
	/config \
	/opt/ubooquity
