#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	config/fonts

# copy config
[[ ! -e /config/preferences.json ]] && \
	cp /defaults/preferences.json /config/preferences.json

# permissions
chown -R abc:abc \
	/config \
	/app/ubooquity
